volumes:
  postgres-data:
  neo4j_data:

services:
  postgres-db:
    image: postgres:15
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  neo4j-db:
    container_name: neo4j-db
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.\\\*,gds.\\\*
      dbms_connector_bolt_listen__address: neo4j-db:7687
      dbms_connector_bolt_advertised__address: neo4j-db:7687
    restart: on-failure
    healthcheck:
      test: cypher-shell --username neo4j --password ${NEO4J_PASSWORD} 'MATCH (n) RETURN COUNT(n);'
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - neo4j_data:/data