server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/LyeshaKorotkevich/alchemy-game-config.git
          clone-on-start: true
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"